device: 'cuda'
amp: True
pin_memory: True
non_blocking: True
prefetch: False

checkpoint_load:
checkpoint_save:
log:
dataset_path: './data'
dataset: 'cifar10'

device: 'cuda:1'

epochs: 100
batch_size: 128
num_workers: 4
lr: 0.0001
lr_scheduler: CosineAnnealingLR
model: vit_b_16

client_optimizer: 'AdamW'
sgd_momentum: 0.75 
wd: 5.0e-4
frequency_save: 0

random_seed: 0

ratio: 0.01
index: 

