device: 'cuda'
amp: True
pin_memory: True
non_blocking: True
prefetch: False

checkpoint_load:
checkpoint_save:
log:
dataset_path: './data'
dataset: 'cifar10'

epochs: 20
batch_size: 128
num_workers: 4
lr: 0.01
lr_scheduler: CosineAnnealingLR
model: vit_b_16

client_optimizer: 'sgd'
sgd_momentum: 0.9 
wd: 5.0e-4
frequency_save: 0

random_seed: 0

ratio: 0.05
index: 
rho_max: 2.0
rho_min: 2.0
label_smoothing: 0.1
alpha: 0.0

